default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "123456"
  host: localhost
  pool: 5

development:
  <<: *default
  database: pagina_web_development

test:
  <<: *default
  database: pagina_web_test

production:
  <<: *default
  database: pagina_web_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
