default: &default
  adapter: postgresql
  encoding: unicode
  username: devserudo
  password: "123456"
  host: localhost
  pool: 5

development:
  <<: *default
  database: pagina_web_development

test:
  <<: *default
  database: pagina_web_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  